#!/bin/sh

# This script runs at every boot of the live system.

udevadm control --reload-rules && udevadm trigger

# HACK: Overrides a built-in live-build hook (1160-openssh-server)
# that disables password auth.
sed -i 's/PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Why not use the built-in live persistence, with persistence.conf?
# Answer: FAT32 permissions issues make it not writable without being
# root all the time. So we just mount it ourselves here.
MEDIUM_PART=$(findmnt --target /run/live/medium --output SOURCE --raw --noheadings)
WRITABLE_PART=${MEDIUM_PART%?}3
mkdir -p /home/folk/folk-live
mount -t vfat $WRITABLE_PART /home/folk/folk-live -o rw,uid=folk,gid=folk || true
